<?php
define("MIN_USERNAME_LENGTH", 3);
define("MIN_PASSWORD_LENGTH", 5);

define("MIN_ARTICLE_TITLE_LENGTH",3);
define("MIN_SUMMARY_LENGTH",5);
define("MAX_SUMMARY_LENGTH",100);
define("MIN_FULL_ARTICLE_LENGTH",200);
define("MAX_FULL_ARTICLE_LENGTH",500);